[package]
cairo-version = "2.12.2"
name = "full_starter_react"
version = "0.1.0"
edition = "2024_07"



[[target.starknet-contract]]
sierra = true
build-external-contracts = ["dojo::world::world_contract::world"]
 
[dependencies]
starknet = "2.12.2"
dojo = "1.7.1"
 
[dev-dependencies]
cairo_test = "2.12.2"
dojo_cairo_test = "1.7.1"
 
[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]
 
[features]
default = []










[cairo]
sierra-replace-ids = true

[scripts]
sepolia = "sozo --profile sepolia clean && sozo --profile sepolia build && sozo --profile sepolia migrate --account-address $DEPLOYER_ACCOUNT_ADDRESS --private-key $DEPLOYER_PRIVATE_KEY --fee strk"





[profile.sepolia]
